services:
  fastapi:
    build:
      context: .
    # Uncomment volume if you want live code sync
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000